module: default
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  upload: index.html
  static_files: index.html
  login: admin
- url: /sounds
  static_dir: sounds
- url: /src
  static_dir: src
- url: /libs
  static_dir: libs
- url: /style
  static_dir: style

skip_files:
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?\..*$
  - ^node_modules$
  - ^sketch_simple_touchboard$
